# Generated by Django 6.0.5 on 2026-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_executiveleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbrief',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
