# Generated by Django 6.0.5 on 2026-06-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projectbrief_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
