# Generated by Django 4.2 on 2026-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_eduskillsdomain_badge_eduskillsdomain_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduskillsdomain',
            name='details_json',
            field=models.TextField(blank=True, default='', help_text='Detailed subpage JSON structure override.'),
        ),
    ]
