# Generated by Django 4.2 on 2026-06-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_eduskillsdomain_details_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Internship Application',
                'verbose_name_plural': 'Internship Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.jobapplication',),
        ),
        migrations.CreateModel(
            name='RegularJobApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.jobapplication',),
        ),
    ]
