# Generated by Django 4.2 on 2026-06-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_internshipapplication_regularjobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='enroll_resumes/'),
        ),
    ]
