# Generated by Django 4.2 on 2026-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_enrollment_experience_enrollment_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
