# Generated by Django 6.0.5 on 2026-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_blogpost_seosetting_testimonial_contact_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveleader',
            name='color_theme',
            field=models.CharField(choices=[('cyan', 'Cyan Glow'), ('purple', 'Purple Glow'), ('green', 'Green Glow'), ('pink', 'Pink/Magenta Glow'), ('blue', 'Blue Glow')], default='cyan', max_length=20),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='initials',
            field=models.CharField(blank=True, help_text='Initials (e.g. RH). Will auto-compute if blank.', max_length=10),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='Whether this person is the founder'),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='quote',
            field=models.TextField(blank=True, help_text='Founder quote or detail statement'),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='stat1_label',
            field=models.CharField(blank=True, help_text='e.g. YEARS BUILDING', max_length=100),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='stat1_value',
            field=models.CharField(blank=True, help_text='e.g. 12+', max_length=50),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='stat2_label',
            field=models.CharField(blank=True, help_text='e.g. VENTURES', max_length=100),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='stat2_value',
            field=models.CharField(blank=True, help_text='e.g. 4', max_length=50),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='stat3_label',
            field=models.CharField(blank=True, help_text='e.g. MENTEES', max_length=100),
        ),
        migrations.AddField(
            model_name='executiveleader',
            name='stat3_value',
            field=models.CharField(blank=True, help_text='e.g. 2K+', max_length=50),
        ),
    ]
