# Generated by Django 4.2 on 2026-06-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_eduskillsmentor_email_alter_apexitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveleader',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio website URL'),
        ),
    ]
