# Generated by Django 4.2 on 2026-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_portfolio_url_to_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('icon_type', models.CharField(default='web', help_text='Icon key — matches CardIcon component types (web, marketing, ai, cyber, uiux, database, cpu, RET, mobile, incubate, growth, seo, social, recruitment, FIN, SUP, HLT, MFG, EDU)', max_length=50)),
                ('tags', models.TextField(blank=True, help_text='One tag per line. Each line becomes a bullet point on the card.')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on public website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('icon_type', models.CharField(default='incubate', help_text='Icon key — matches CardIcon component types', max_length=50)),
                ('accent_color', models.CharField(default='#0ea5e9', help_text='Hex colour for the card accent (e.g. #0ea5e9)', max_length=20)),
                ('tags', models.TextField(blank=True, help_text='One tag per line. Each line becomes a bullet point on the card.')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on public website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
