# Generated by Django 4.2 on 2026-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_service_and_solution_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('successful_responses', models.IntegerField(default=0)),
                ('failed_responses', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('top_intents', models.JSONField(blank=True, default=dict)),
                ('unique_sessions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user_query', models.TextField(blank=True)),
                ('feedback', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
