# Generated by Django 4.2 on 2026-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_chatbotanalytics_chatbotfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='live_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
