# Generated by Django 4.2 on 2026-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_blogpost_github_url_blogpost_live_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduskillsdomain',
            name='curriculum_image',
            field=models.ImageField(blank=True, help_text='Curriculum image file that users can download.', null=True, upload_to='curriculum/'),
        ),
    ]
