# Generated by Django 4.2 on 2026-06-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_eduskillsdomain_curriculum_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('certificate_photo', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('blockchain_block', models.CharField(blank=True, default='#1,902,482', max_length=100)),
                ('tx_hash', models.CharField(blank=True, default='0x4a9d7b23c2ef5c10b981ec4899f8be78b5cf6a27', max_length=200)),
                ('smart_contract', models.CharField(blank=True, default='0x00e5ff8b5cf6ec489910b981f59e0b4f9cffbf5c', max_length=200)),
                ('issuer', models.CharField(default='Hadescore Apex & Technologies Certification Board', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
