# Generated by Django 4.2 on 2026-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_photo',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
