# Generated by Django 4.2 on 2026-06-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_certificate_certificate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduskillsmentor',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Associated placement domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='api.eduskillsdomain'),
        ),
    ]
