# Generated by Django 4.2 on 2026-06-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_eduskillsmentor_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveleader',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Associated placement domain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eduskillsdomain'),
        ),
        migrations.AlterField(
            model_name='eduskillsmentor',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Associated placement domain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eduskillsdomain'),
        ),
        migrations.AlterField(
            model_name='executiveleader',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Contact email address', max_length=254),
        ),
    ]
