# Generated by Django 4.2 on 2026-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_executiveleader_domain_alter_eduskillsmentor_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduskillsdomain',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g. AI / ML, Fullstack, Cyber - Used to match mentors', max_length=100),
        ),
    ]
